// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeAccelerationProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeAccelerationProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeAcceleration_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeAcceleration_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeAccelerationProto_2eproto() {
  protobuf_AddDesc_CarlifeAccelerationProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeAccelerationProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeAcceleration_descriptor_ = file->message_type(0);
  static const int CarlifeAcceleration_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeAcceleration, accx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeAcceleration, accy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeAcceleration, accz_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeAcceleration, timestamp_),
  };
  CarlifeAcceleration_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeAcceleration_descriptor_,
      CarlifeAcceleration::default_instance_,
      CarlifeAcceleration_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeAcceleration, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeAcceleration, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeAcceleration));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeAccelerationProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeAcceleration_descriptor_, &CarlifeAcceleration::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeAccelerationProto_2eproto() {
  delete CarlifeAcceleration::default_instance_;
  delete CarlifeAcceleration_reflection_;
}

void protobuf_AddDesc_CarlifeAccelerationProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\036CarlifeAccelerationProto.proto\022\032com.ba"
    "idu.carlife.protobuf\"R\n\023CarlifeAccelerat"
    "ion\022\014\n\004accX\030\001 \002(\001\022\014\n\004accY\030\002 \002(\001\022\014\n\004accZ\030"
    "\003 \002(\001\022\021\n\ttimeStamp\030\004 \001(\004", 144);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeAccelerationProto.proto", &protobuf_RegisterTypes);
  CarlifeAcceleration::default_instance_ = new CarlifeAcceleration();
  CarlifeAcceleration::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeAccelerationProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeAccelerationProto_2eproto {
  StaticDescriptorInitializer_CarlifeAccelerationProto_2eproto() {
    protobuf_AddDesc_CarlifeAccelerationProto_2eproto();
  }
} static_descriptor_initializer_CarlifeAccelerationProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeAcceleration::kAccXFieldNumber;
const int CarlifeAcceleration::kAccYFieldNumber;
const int CarlifeAcceleration::kAccZFieldNumber;
const int CarlifeAcceleration::kTimeStampFieldNumber;
#endif  // !_MSC_VER

CarlifeAcceleration::CarlifeAcceleration()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeAcceleration::InitAsDefaultInstance() {
}

CarlifeAcceleration::CarlifeAcceleration(const CarlifeAcceleration& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeAcceleration::SharedCtor() {
  _cached_size_ = 0;
  accx_ = 0;
  accy_ = 0;
  accz_ = 0;
  timestamp_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeAcceleration::~CarlifeAcceleration() {
  SharedDtor();
}

void CarlifeAcceleration::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeAcceleration::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeAcceleration::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeAcceleration_descriptor_;
}

const CarlifeAcceleration& CarlifeAcceleration::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeAccelerationProto_2eproto();
  return *default_instance_;
}

CarlifeAcceleration* CarlifeAcceleration::default_instance_ = NULL;

CarlifeAcceleration* CarlifeAcceleration::New() const {
  return new CarlifeAcceleration;
}

void CarlifeAcceleration::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    accx_ = 0;
    accy_ = 0;
    accz_ = 0;
    timestamp_ = GOOGLE_ULONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeAcceleration::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double accX = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &accx_)));
          set_has_accx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_accY;
        break;
      }

      // required double accY = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_accY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &accy_)));
          set_has_accy();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(25)) goto parse_accZ;
        break;
      }

      // required double accZ = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_accZ:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &accz_)));
          set_has_accz();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_timeStamp;
        break;
      }

      // optional uint64 timeStamp = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeAcceleration::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required double accX = 1;
  if (has_accx()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->accx(), output);
  }

  // required double accY = 2;
  if (has_accy()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->accy(), output);
  }

  // required double accZ = 3;
  if (has_accz()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->accz(), output);
  }

  // optional uint64 timeStamp = 4;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->timestamp(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeAcceleration::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required double accX = 1;
  if (has_accx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->accx(), target);
  }

  // required double accY = 2;
  if (has_accy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->accy(), target);
  }

  // required double accZ = 3;
  if (has_accz()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->accz(), target);
  }

  // optional uint64 timeStamp = 4;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->timestamp(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeAcceleration::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required double accX = 1;
    if (has_accx()) {
      total_size += 1 + 8;
    }

    // required double accY = 2;
    if (has_accy()) {
      total_size += 1 + 8;
    }

    // required double accZ = 3;
    if (has_accz()) {
      total_size += 1 + 8;
    }

    // optional uint64 timeStamp = 4;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->timestamp());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeAcceleration::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeAcceleration* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeAcceleration*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeAcceleration::MergeFrom(const CarlifeAcceleration& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_accx()) {
      set_accx(from.accx());
    }
    if (from.has_accy()) {
      set_accy(from.accy());
    }
    if (from.has_accz()) {
      set_accz(from.accz());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeAcceleration::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeAcceleration::CopyFrom(const CarlifeAcceleration& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeAcceleration::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void CarlifeAcceleration::Swap(CarlifeAcceleration* other) {
  if (other != this) {
    std::swap(accx_, other->accx_);
    std::swap(accy_, other->accy_);
    std::swap(accz_, other->accz_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeAcceleration::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeAcceleration_descriptor_;
  metadata.reflection = CarlifeAcceleration_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
