// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeAccelerationProto.proto

#ifndef PROTOBUF_CarlifeAccelerationProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeAccelerationProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeAccelerationProto_2eproto();
void protobuf_AssignDesc_CarlifeAccelerationProto_2eproto();
void protobuf_ShutdownFile_CarlifeAccelerationProto_2eproto();

class CarlifeAcceleration;

// ===================================================================

class CarlifeAcceleration : public ::google::protobuf::Message {
 public:
  CarlifeAcceleration();
  virtual ~CarlifeAcceleration();

  CarlifeAcceleration(const CarlifeAcceleration& from);

  inline CarlifeAcceleration& operator=(const CarlifeAcceleration& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeAcceleration& default_instance();

  void Swap(CarlifeAcceleration* other);

  // implements Message ----------------------------------------------

  CarlifeAcceleration* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeAcceleration& from);
  void MergeFrom(const CarlifeAcceleration& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double accX = 1;
  inline bool has_accx() const;
  inline void clear_accx();
  static const int kAccXFieldNumber = 1;
  inline double accx() const;
  inline void set_accx(double value);

  // required double accY = 2;
  inline bool has_accy() const;
  inline void clear_accy();
  static const int kAccYFieldNumber = 2;
  inline double accy() const;
  inline void set_accy(double value);

  // required double accZ = 3;
  inline bool has_accz() const;
  inline void clear_accz();
  static const int kAccZFieldNumber = 3;
  inline double accz() const;
  inline void set_accz(double value);

  // optional uint64 timeStamp = 4;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimeStampFieldNumber = 4;
  inline ::google::protobuf::uint64 timestamp() const;
  inline void set_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeAcceleration)
 private:
  inline void set_has_accx();
  inline void clear_has_accx();
  inline void set_has_accy();
  inline void clear_has_accy();
  inline void set_has_accz();
  inline void clear_has_accz();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double accx_;
  double accy_;
  double accz_;
  ::google::protobuf::uint64 timestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeAccelerationProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeAccelerationProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeAccelerationProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeAcceleration* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeAcceleration

// required double accX = 1;
inline bool CarlifeAcceleration::has_accx() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeAcceleration::set_has_accx() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeAcceleration::clear_has_accx() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeAcceleration::clear_accx() {
  accx_ = 0;
  clear_has_accx();
}
inline double CarlifeAcceleration::accx() const {
  return accx_;
}
inline void CarlifeAcceleration::set_accx(double value) {
  set_has_accx();
  accx_ = value;
}

// required double accY = 2;
inline bool CarlifeAcceleration::has_accy() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CarlifeAcceleration::set_has_accy() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CarlifeAcceleration::clear_has_accy() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CarlifeAcceleration::clear_accy() {
  accy_ = 0;
  clear_has_accy();
}
inline double CarlifeAcceleration::accy() const {
  return accy_;
}
inline void CarlifeAcceleration::set_accy(double value) {
  set_has_accy();
  accy_ = value;
}

// required double accZ = 3;
inline bool CarlifeAcceleration::has_accz() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CarlifeAcceleration::set_has_accz() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CarlifeAcceleration::clear_has_accz() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CarlifeAcceleration::clear_accz() {
  accz_ = 0;
  clear_has_accz();
}
inline double CarlifeAcceleration::accz() const {
  return accz_;
}
inline void CarlifeAcceleration::set_accz(double value) {
  set_has_accz();
  accz_ = value;
}

// optional uint64 timeStamp = 4;
inline bool CarlifeAcceleration::has_timestamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CarlifeAcceleration::set_has_timestamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CarlifeAcceleration::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CarlifeAcceleration::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 CarlifeAcceleration::timestamp() const {
  return timestamp_;
}
inline void CarlifeAcceleration::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeAccelerationProto_2eproto__INCLUDED
